export const ascendaIAStrings = {
  page: {
    title: "AscendaIA — Quiz Generator",
    subtitle: "Generate activities from a topic, a YouTube video, or a text document.",
    breadcrumbHome: "Content",
    breadcrumbCurrent: "AscendaIA",
  },
  inputs: {
    topicLabel: "Topic",
    topicPlaceholder: "What should the quiz be about?",
    youtubeLabel: "YouTube link",
    youtubePlaceholder: "https://www.youtube.com/watch?v=...",
    uploadLabel: "Upload .txt document",
    uploadHelper: "Upload a UTF-8 .txt file up to 5MB.",
    uploadButton: "Browse .txt",
    removeFile: "Remove file",
    fileTooLarge: "File must be 5MB or less.",
    fileInvalidType: "Only plain text (.txt) files are supported.",
    youtubeInvalid: "Enter a valid YouTube URL.",
    sourceRequired: "Provide a topic, a YouTube URL, or upload a .txt file.",
  },
  levels: {
    easy: {
      code: "easy",
      title: "Iniciante",
      summaryLabel: "Easy",
      description: "Quick wins and onboarding questions.",
      accent: "sky",
      defaultCount: 4,
    },
    intermediate: {
      code: "intermediate",
      title: "Intermediário",
      summaryLabel: "Intermediate",
      description: "Scenario-based reasoning and application.",
      accent: "violet",
      defaultCount: 4,
    },
    advanced: {
      code: "advanced",
      title: "Avançado",
      summaryLabel: "Advanced",
      description: "Deep strategic and architectural challenges.",
      accent: "fuchsia",
      defaultCount: 2,
    },
  },
  summary: {
    heading: "Request summary",
    description: "Adjust the distribution before generating with AscendaIA.",
    totalLabel: "Total requested",
    totalHint: "Number of items to generate across all levels.",
    chipsLabel: "Level breakdown",
    disabledHint: "Provide a source and enable at least one level to continue.",
    generate: "Generate",
    generating: "Generating…",
  },
  preview: {
    heading: "Preview",
    emptyState: "No quiz generated yet.",
    description: "Generated questions are grouped by level. Review before saving.",
    columnLabels: {
      easy: "Basic",
      intermediate: "Intermediate",
      advanced: "Advanced",
    },
    totalItems: "{{count}} items",
  },
  actions: {
    discard: "Discard",
    save: "Save quiz",
    saved: "Quiz saved locally!",
    saveError: "Unable to save the quiz locally.",
  },
  feedback: {
    generationError: "Something went wrong while generating the quiz. Try again.",
  },
  fallbacks: {
    youtubeTopic: "YouTube source",
    documentTopic: "Text document",
  },
  limits: {
    maxItemsPerLevel: 50,
    maxFileSizeBytes: 5 * 1024 * 1024,
  },
};
